language: node_js
node_js:
  - '0.10'
  - '0.12'

deploy:
  provider: npm
  email: open-source@goodeggs.com
  api_key:
    secure: "rCTxNFlfCvpDOfwGK6hZEZfknUxXR6w1eHKD9Ioqraf9Vg9+I8rXHYy5a8+fjOPghEWwW6isoAQ3eVk7Xuu5rkml5k2wSve4dN1q6sSW96CUI/s9nORgCU1foNhmKAHrwKsEPXmmYp/1HoB/bRUvwISP/ejuhMWG1wOTztSVPh/+20tq8bvbv1qs8Vuorta63ddoqxOpt8fDBFpFMQK9YJuv8CTJSTmBuiPvmyfDXHFrbzQuONcxPXc2R9bmfKZkpXjRkxZa3uYk9EXgK10D5yrrjuWhfXXi7HMeqkHG2apErS3m1yoRcsjz5m8dbvtoOt/7t3cgAzFvKuftysdoWFf5lyEKcD9LjNENMKarT3PfZr5u8uWOunLq7EoJ5alhrFud8Dqd4hRgsSy0SEWjEr5eNIpl4AXd9HTz6OwX+OXa4+MOyrlq26ebVf374Tz8eRZ6N3lr8jCEIc98a0+rsACSmJBraWcGqA/vbO1Tt8RH3C2Mnm16Q+sN+tMuPKPrruytMWyBIr1m+g1uA2Tb27yhvrBpq7XZZTAovE5LeFxBQy0Kjb243z7prYLZ9vYCZBoALnJPLLz9egSJmIMd6nxn/KibghR3qsPWjA1ESlClLrfLLqT47g27r7ucrTQtgdCbZ4UM1Gw0OHGDYbpp3PiCnZr2L8i2h7ecml8fYrI="
  clean_up: false
  on:
    tags: true
    all_branches: true
